name: Build
on:
  push:

jobs:
  linux:
    if: false
    runs-on: ubuntu-latest
    env:
      QT_SELECT: 5

    steps:
      - uses: actions/checkout@v2

      - name: install build dependencies
        run: |
          sudo apt install g++ make ccache qttools5-dev-tools libqt5xmlpatterns5-dev libqt5svg5-dev

      - name: build
        run: |
          mkdir /home/runner/local
          qmake PREFIX=/home/runner/local Seamly2D.pro
          make
          make install

      - name: archive
        uses: actions/upload-artifact@v2
        with:
          name: seamly2d-linux
          path: /home/runner/local

  windows:
    runs-on: windows-latest
    env:
      QT_SELECT: 5

    steps:
      - uses: actions/checkout@v2

      - uses: ilammy/msvc-dev-cmd@v1

      - name: install build dependencies
        uses: jurplel/install-qt-action@v2

      - name: build
        run: |
          qmake Seamly2D.pro
          make

      - name: archive
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: makefile-windows
          path: Makefile
