name: Test windows

on:
  push:
    branches:
      - develop
env:
  QT_SELECT: 5
  QT_VERSION: '5.13.2' # quotes required or YAML parser will interpret as float

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: '14.26.28801'
      - uses: jurplel/install-qt-action@v2
        with:
          version: ${{ env.QT_VERSION }}
      - name: build
        env:
          MSVC: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.26.28801\bin\Hostx86\x86\

        #ls "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.26.28801"
        #$Env:Include += "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.26.28801\Include";
        # $Env:Path += ";$Env:MSVC"
        #& $Env:Qt5_Dir\bin\qmake.exe Seamly2D.pro -r CONFIG+=no_ccache CONFIG+=noDebugSymbols
        run: |
          qmake.exe Seamly2D.pro -r CONFIG+=no_ccache CONFIG+=noDebugSymbols
          nmake.exe
      - name: create & code sign installer
        run: |
          mkdir ..\windows-build
          Get-ChildItem -Recurse -Include *.exe,*.dll | % { Copy-Item $_.FullName -force -destination ..\windows-build }
          windeployqt.exe --libdir ..\windows-build --plugindir ..\windows-build --release ..\windows-build\seamly2d.exe
          windeployqt.exe --force --libdir ..\windows-build --plugindir ..\windows-build --release ..\windows-build\seamlyme.exe
          copy .\dist\seamly2d-installer.nsi ..\windows-build\
          copy .\dist\win\VC_redist.x86.exe ..\windows-build\
          copy .\dist\win\VC_redist.x64.exe ..\windows-build\

          cd ..\windows-build\
          & 'C:\Program Files (x86)\NSIS\makensis.exe' seamly2d-installer.nsi
          cd ..\Seamly2D
          copy ..\windows-build\seamly2d-installer.exe .\
      - name: upload seamly2d-installer
        uses: actions/upload-artifact@v2
        with:
          name: installer
          path: seamly2d-installer.exe
